.flowconfig
__examples__/symlinked_checksums_need_updating/a.js
__examples__/symlinked_checksums_need_updating/b.py
__examples__/symlinked_checksums_need_updating/target_does_not_exist.js
package.json
src/__tests__/__snapshots__/integration_test.js.snap
src/__tests__/cli_test.js
src/__tests__/clone-as-unfixable_test.js
src/__tests__/generate-marker-edges_test.js
src/__tests__/get-markers-from-files_test.js
src/__tests__/parse-file_test.js
src/__tests__/process-cache_test.js
src/cli.js
src/clone-as-unfixable.js
src/error-codes.js
src/generate-marker-edges.js
src/get-markers-from-files.js
src/parse-file.js
src/process-cache.js
src/types.js
yarn.lock

Fixes #7 
In this update, we allow for file aliases so that they are only parsed and written once, total, and so that tags referencing a symlinked file act as though they reference the actual file.

Ensure that we cope with symlinked files properly

---

flow-typed/npm/minimatch_v3.x.x.js
package.json
src/__tests__/get-files_test.js
src/get-files.js

The current implementation was incredibly naïve and slow. By updating to minimatch, we don't look for ignore files on the filesystem, but instead, filter the paths we already got fro `glob`.

Use minimatch to filter for ignored globs

---

.github/workflows/nodejs.yml

Summary
Specify node 8 version to workaround Windows issue in Github Actions
Issues
This works around actions/setup-node#27 and actions/virtual-environments#42

Make sure node 8 will be recent for when we finally use windows again

---

__examples__/checksums_need_updating/a.js
src/__tests__/__snapshots__/integration_test.js.snap
src/__tests__/validate-and-fix_test.js
src/generate-marker-edges.js
src/process-cache.js
src/validate-and-fix.js

**Summary**
- Indentation of start tag line is now written out when updating tags
- Output puts blank line before command
- Fixed a bad test case
**Issues**
Fixes #82

Ensure fix includes indentation of start tag

---

CONTRIBUTING.md
src/get-markers-from-files.js
src/validate-and-fix.js

**Summary**
Turns out, when there are no broken edges, we were still opening and writing files when `-u` is specified. That's bad. So, we fixed it.
**Issues**
#219 
**Details**
Also fixed a couple of typos in docs and code.

[#219] Make sure we don't bother writing files that don't need updating

---

src/__tests__/__snapshots__/integration_test.js.snap
src/__tests__/generate-marker-edges_test.js
src/__tests__/marker-parser_test.js
src/__tests__/validate-and-fix_test.js
src/__tests__/validate-and-report_test.js
src/generate-marker-edges.js
src/marker-parser.js
src/types.js
src/validate-and-fix.js
src/validate-and-report.js

This changes the `generateMarkerEdges` function to treat missing
target files or markers as broken edges rather than reporting them
directly. The validators have then been updated to understand this
kind of broken edge and report them. This will allow for other kinds
of validators to handle this kind of error with a more helpful message
(such as those that could be used to support linters).
This also addresses an issue that Flow can't catch due to poor core
typing. It turns out that regex optional groups can come back as
undefined in a match, even though the type is a string. So, now
the two optional groups in our tag parsing are coerced to empty strings
in the case that they aren't present (which is what was expected).

All Errors handled by file validators

---

README.md

GitHub doesn't support this yet for the official dependabot: https://github.com/dependabot/dependabot-core/issues/1912

Remove dependabot badge

---

src/__tests__/cli_test.js
src/cli.js

**Summary**
I've had trouble running `checksync` for quite a while. I had to resort to running it by passing the entrypoint file to node manually `node path/to/checksync.js`.  
The error I'd see is this:
```
(node:45761) UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, scandir '/Users/jeremy/.volta/tools/image/packages/checksync/bin/checksync'
(node:45761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) …
```

Fix handling of cli arg that is symlink

---

.babelrc
.github/workflows/nodejs.yml
.prettierignore
package.json

Fixes #643 and fixes #642
Includes #669 since I'm comparing against `main` to trigger the test runs.

Add support for Node16 and remove Node10

---

.github/workflows/codeql-analysis.yml

See https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

[🔥AUDIT🔥] Update CodeQL to v2

---

.changeset/many-geese-unite.md
.eslintrc.js
src/__tests__/__snapshots__/format.test.ts.snap
src/__tests__/__snapshots__/integration.test.ts.snap
src/__tests__/__snapshots__/string-logger.test.ts.snap
src/__tests__/file-reference-logger.test.ts
src/__tests__/get-files.test.ts
src/file-reference-logger.ts
src/format.ts

This makes some changes to the console logging so that it is easier to read.
- Replace message label left-padding with right-padding
- Move the message to a new line below the label and file reference information
- Move each sentence in an message to a new line
Also updates how message labels are handled internally for easier maintenance.
`yarn test`

Improve console output formatting for readability

---

.changeset/lovely-apples-cough.md
.codecov.yml
src/__tests__/__snapshots__/cli.test.ts.snap
src/__tests__/__snapshots__/integration.test.ts.snap
src/__tests__/check-sync.test.ts
src/__tests__/cli.test.ts
src/__tests__/determine-options.test.ts
src/__tests__/exit.test.ts
src/__tests__/fix-file.test.ts
src/__tests__/help.test.ts
src/__tests__/integration.test.ts
src/__tests__/main.test.ts
src/__tests__/maybe-report-error.test.ts
src/__tests__/output-sink.test.ts
src/__tests__/process-cache.test.ts
src/__tests__/set-cwd.test.ts
src/check-sync.ts
src/cli.ts
src/determine-options.ts
src/error-codes.ts
src/exit-codes.ts
src/exit.ts
src/generate-errors-for-file.ts
src/get-markers-from-files.ts
src/help.ts
src/marker-parser.ts
src/output-sink.ts
src/parse-file.ts
src/set-cwd.ts

This adds a new `--cwd` argument to override the current working directory that checksync uses.
More importantly, it now sets the current working directory to the location of the configuration file, if one is loaded. This ensures that paths/globs specified in a configuration file are interpreted relative to the configuration file, not the current working directory, which makes it a lot easier to reason about the configuration file definition.
Issue: fixes #1262
`yarn test`

Add cwd arg and cwd behavior

---

.changeset/chilled-sheep-shop.md
rollup.config.js

Before this change, we were not inlining our external deps. This was down to the `plugin-node-resolve` behavior once the `extensions` array was given to add support for TypeScript files as I had not included the defaults. The defaults are now included.
Issue: XXX-XXXX
`yarn build` and verify that it works.

[🔥AUDIT🔥] [fixrollup] Fix rollup configuration

---

.changeset/hungry-fans-study.md
package.json

Apparently, in some situations, the engines is being used to block npx (it works locally for me, but not in some Actions). Removing the npm version check to fix this.
Issue: XXX-XXXX
Release and see that it works for webapp checks

[🔥AUDIT🔥] [fixengines] Make sure npx works for all cases

---

.changeset/smooth-cats-itch.md
__examples__/empty_tag/a.js
__examples__/empty_tag/b.js
jest.config.js
src/__tests__/__snapshots__/integration.test.ts.snap
src/__tests__/check-sync.test.ts
src/__tests__/default-options.test.ts
src/__tests__/fix-file.test.ts
src/__tests__/get-markers-from-files.test.ts
src/__tests__/options-from-args.test.ts
src/__tests__/parse-file.test.ts
src/checksync.schema.json
src/cli.ts
src/default-options.ts
src/options-from-args.ts
src/parse-file.ts
src/types.ts

This adds a new configuration option to allow empty tags, and implements this.
This fixes #1980
`yarn test`

[emptytags] Add allowEmptyTags config

---

.changeset/eighty-dolphins-run.md
src/__tests__/__snapshots__/cli.test.ts.snap
src/__tests__/help.test.ts
src/cli.ts
src/help.ts

Fixes a rookie mistake I made in the last patch.
`yarn test`
`./dev/checksync --help`
`./dev/checksync -a .` -> shouldn't see empty tag error

[🔥AUDIT🔥] [audit.fixcliarg] Make sure arg is documented and is boolean

---

.changeset/healthy-onions-drop.md
package.json
src/__tests__/__snapshots__/integration.test.ts.snap
src/__tests__/cli.test.ts
src/cli.ts
src/determine-options.ts
src/options-from-args.ts
src/parse-args.ts
yarn.lock

It turns out that we were overriding default values and explicit configuration with the default argument values for our boolean flags. This was down to minimist defaulting missing boolean args to `false` instead of not providing them. So, I've done a minimal transition to yargs instead.
In a future release, we can leverage more of yargs features, but for now, I've tried to keep things as similar as possible to previous releases.
However, given that this is a change in behaviour, I'm putting it out as a major release in case anyone was inadvertently relying on the broken processing of args and config.
`yarn test`
Also, try running with a config where a boolean option is set to true and see that it is respected.

[argparsingfix] Fix issue where implicit args override explicit config

---

.changeset/unlucky-brooms-pretend.md
src/parse-args.ts

Turns out, if you want to turn off the default handling of `--help` and `--version`, then provide custom handling of these args, you have to do it in that order. 🤦
`./dev/checksync.dev.js --version`
`./dev/checksync.dev.js --help
`

[🔥AUDIT🔥] [audit.fixhelpandversionargs] Properly configure yargs for custom help and version

---

.changeset/puny-eggs-carry.md
.gitignore
bin/gen-integration-test-logs.ts
src/__tests__/__snapshots__/integration.test.ts.snap
src/__tests__/check-sync.test.ts
src/__tests__/default-options.test.ts
src/__tests__/exit-error.test.ts
src/__tests__/fix-file.test.ts
src/__tests__/generate-errors-for-file.test.ts
src/__tests__/get-markers-from-files.test.ts
src/__tests__/integration-test-support.test.ts
src/__tests__/integration.test.ts
src/__tests__/load-cache.test.ts
src/__tests__/options-from-args.test.ts
src/__tests__/output-cache.test.ts
src/__tests__/parse-file.test.ts
src/build-cache.ts
src/check-sync.ts
src/default-options.ts
src/exit-codes.ts
src/exit-error.ts
src/integration-test-support.ts
src/load-cache.ts
src/normalize-separators.ts
src/options-from-args.ts
src/output-cache.ts
src/parse-args.ts
src/types.ts

This adds some new arguments so that we can split out the parsing of tags (aka markers) from files, and the processing of the markers. This will speed up our integration tests, but potentially opens the door for other uses. For example, the upcoming migration tool could be run using a cache so that we can re-run it with the same cache without having to re-parse all the same files, which will make it easier for me to test against webapp's complex tagging without having to wait to parse all the files every time.
This is not some cache to speed up regular checksync usage (like, say, how babel uses a cache). That would take a lot more effort (like working out cache invalidation, etc.) and isn't planned at this time.
The output cache does not include the settings used to create it, so it …

[somewhatabstract/issue2039] Add cache support

---

.changeset/quiet-tigers-scream.md
src/__tests__/generate-errors-for-file.test.ts
src/__tests__/get-markers-from-files.test.ts
src/__tests__/parse-file.test.ts
src/errors.ts
src/fix-file.ts
src/format-sync-tag-start.ts
src/generate-errors-for-file.ts
src/get-markers-from-files.ts
src/marker-parser.ts
src/parse-file.ts

This is a tidy-up task before I add the last bit of migration stuff. It isn't perfect but it moves the error creation to helper functions to make things a little more consistent and help spot patterns.
Trying to work out the smallest set of args to send was a little trying so I didn't try too hard on this pass. I expect a bigger refactor will be needed to make this nicer; such as not including full text messages in the details but letting those be calculated at a later stage. Some clear areas of confusion are around when a target path is used for the tag itself (needs to be relative to the root marker), or when it is used to report to the user (needs to be relative to the current working directory).
Issue: FEI-6294
`pnpm test` to show that things are good.

[fei6294.2.errorcodes] Move error creation to helper functions

---

.changeset/public-beers-dance.md
.checksyncrc.json
__examples__/migrate_all/example-1.js
__examples__/migrate_all/example-2.js
jest.config.js
package.json
pnpm-lock.yaml
src/__tests__/__snapshots__/integration.test.ts.snap
src/__tests__/determine-migration.test.ts
src/__tests__/generate-errors-for-file.test.ts
src/__tests__/get-launch-string.test.ts
src/__tests__/integration-test-support.test.ts
src/__tests__/load-configuration-file.test.ts
src/__tests__/load-migration-config.test.ts
src/__tests__/options-from-args.test.ts
src/determine-migration.ts
src/determine-options.ts
src/errors.ts
src/generate-errors-for-file.ts
src/integration-test-support.ts
src/load-migration-config.ts
src/main.ts
src/options-from-args.ts
src/parse-args.ts
src/polyfills.ts
src/types.ts
tsconfig-shared.json

This makes the following changes:
- Fixes log output of options by removing use of `Map` instance
- Removes the iterator-helpers polyfill (the replacement of the `Map` instance with a POJO means we use `Object.entries` and the Array-based helpers)
- Adds a new argument, `migrate` to override the migration mode of the configuration file
- Properly defaults the migration mode (previously, it wasn't getting defaulted correctly)
- Adds an integration test for the new migrate=all mode
This completes the new sync-tag format work, and closes #2036 and #2009. We can release v8 after this lands.
Issue: FEI-6294, closes #2036 and #2009
`pnpm test`
- Run `./bin/checksync.dev.ts --migrate=all __examples__/migrate_all`

[fei6294.3.modeall] Implement migrate all mode

---

.changeset/icy-geese-laugh.md
.github/workflows/nodejs.yml
package.json
pnpm-lock.yaml
rollup.config.mjs
src/__tests__/__snapshots__/format.test.ts.snap
src/__tests__/ancesdir-or-currentdir.test.ts
src/__tests__/cli.test.ts
src/__tests__/format.test.ts
src/__tests__/output-sink.test.ts
src/ancesdir-or-currentdir.ts
src/cli.ts
src/format.ts
src/output-sink.ts

This updates to the latest ancesdir, and also adds some clearer error output if it fails. In addition, we now include the stack for unexpected errors, and the output sink is properly handling path errors so that we get a more consistent output.
So, now for the common case like the one that led to this, folks will see output like:
```
Error    __examples__/content_after_start/a.js
Could not parse /Users/jeffyates/git/checksync/__examples__/content_after_start/a.js: Unable to locate directory containing marker file "madeupmarkerfile" from starting location "/Users/jeffyates/git/checksync/__examples__/content_after_start/a.js"
Error    __examples__/content_after_start/b.py
Could not parse /Users/jeffyates/git/checksync/__examples__/content_after_start/b.py: Unable to locate directory …
```

Update ancesdir and add nicer error output

---

.changeset/tall-pugs-check.md
src/__tests__/__snapshots__/cli.test.ts.snap
src/__tests__/cli.test.ts
src/cli.ts

It turns out there was a bug in checksync where we were forcing color output even if the environment variable to disable it was present. This fixes that and adds support for the common `NO_COLOR=0` environment variable.
Issue: Closes #2116
`pnpm test`
I also ran `NO_COLOR=1 pnpm ./bin/checksync.dev.js --help` and `FORCE_COLOR=0 pnpm ./bin/checksync.dev.js --help` to verify that the color output was disabled.
And also `pnpm ./bin/checksync.dev.js --help` to verify that the color output was enabled.

Make sure that color output can be turned off

---

.changeset/warm-actors-divide.md
__examples__/dot_paths_with_correct_checksum/.checkme1
__examples__/dot_paths_with_correct_checksum/.checkme2
src/__tests__/__snapshots__/integration.test.ts.snap
src/__tests__/check-sync.test.ts
src/__tests__/default-options.test.ts
src/__tests__/fix-file.test.ts
src/__tests__/get-files.test.ts
src/__tests__/get-markers-from-files.test.ts
src/__tests__/options-from-args.test.ts
src/__tests__/parse-file.test.ts
src/build-cache.ts
src/checksync.schema.json
src/default-options.ts
src/get-files.ts
src/options-from-args.ts
src/parse-args.ts
src/types.ts

This makes it so that dot paths like `./.eslintrc` are included when parsing the globs of what files to include. This can be disabled with configuration or arguments via the `includeDotPaths` option.
Issue: Closes #2117
`pnpm test`
I've added a new ingegration test that would fail if `includeDotPaths` were false.

Include dot paths

---

.changeset/soft-points-poke.md
src/parse-args.ts

This was preventing `checksync --help` from working, as the default is seen as the arg being used and so then it says it can't be used with `--help`. We want to still prevent them being combined as it doesn't make sense, so we remove the default for the arg and instead rely on our internal default logic to handle setting that default value. This is what we want anyway as we don't want the config to be overridden by the default arg.
Issue: XXX-XXXX
`pnpm test`

[🔥AUDIT🔥] Remove arg default for includeDotPaths

---

.changeset/clean-moose-taste.md
__examples__/dot_paths_with_correct_checksum/.checkme1
__examples__/dot_paths_with_correct_checksum/.checkme2
src/__tests__/__snapshots__/cli.test.ts.snap
src/__tests__/__snapshots__/integration.test.ts.snap
src/__tests__/check-sync.test.ts
src/__tests__/default-options.test.ts
src/__tests__/fix-file.test.ts
src/__tests__/get-files.test.ts
src/__tests__/get-markers-from-files.test.ts
src/__tests__/help.test.ts
src/__tests__/options-from-args.test.ts
src/__tests__/parse-file.test.ts
src/build-cache.ts
src/checksync.schema.json
src/default-options.ts
src/get-files.ts
src/help.ts
src/options-from-args.ts
src/parse-args.ts
src/types.ts

`includeDotPaths` was a mistake. It ends up including things like `.git` which is slow and messy. Instead, folks should explicitly opt in each dot path they want instead. So, this basically puts us back to v8 behavior, but with the non-dotfiles features that were added to v9. v9 bad, v10 good.
Issue: XXX-XXXX
`pnpm test`

[🔥AUDIT🔥] Remove includeDotPaths and update help instead

---

.changeset/rotten-deer-begin.md
.vscode/launch.json
package.json
pnpm-lock.yaml
src/__tests__/__snapshots__/integration.test.ts.snap
src/get-files.ts
src/ignore-file-globs-to-allow-predicate.ts

This makes sure we don't follow symlinks when searching for ignore files or files. We shouldn't need to follow symlinks as the target of relevant symlinks should be in the codebase being scanned, anyway.
Issue: #2134
`pnpm test` should pass.
I also ran this against the Khan webapp repo where we were encountering issues and it appears to work.

Don't follow symlinks in glob searches
